# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0000be33082d5e330515fb586f842b69a13f9af230394c54c726663749af821498336bee2ef710169736b5dff61d0c10fbf4294ccd3f64d76fb1ca08296c52f2

test:
  secret_key_base: 6fbe925bc4db3414b24d87f78c927565f7174514bb047789cae56c99f5fdff5fb15d9c65abd8499a800ec255e99f4a0e2974906d687dc45f3d9915b1a20457cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
